jax:
  url: https://github.com/google/jax.git
  tracking_ref: main
  latest_verified_commit: a3ed1b2f6ada629cbf4945c0122876590dfbbbaa
  mode: git-clone
xla:
  url: https://github.com/openxla/xla.git
  tracking_ref: main
  latest_verified_commit: 48a1641f1f9ac266ad9e9f4ba5345b3821ba086e
  mode: git-clone
flax:
  url: https://github.com/google/flax.git
  mirror_url: https://github.com/nvjax-svc-0/flax.git
  tracking_ref: main
  mode: git-clone
  patches:
    pull/3340/head: file://patches/flax/PR-3340.patch # Add Sharding Annotations to Flax Modules
  latest_verified_commit: 2fe9c869fade230c410653180c8fba2eb501e7d7
transformer-engine:
  url: https://github.com/NVIDIA/TransformerEngine.git
  tracking_ref: main
  latest_verified_commit: 0803102751cfb099f71348efddc50cc0664cda89
  mode: git-clone
pydantic:
  version: X.Y.Z
  mode: pip-constraint
dllogger:
  url: https://github.com/NVIDIA/dllogger.git
  tracking_ref: master
  latest_verified_commit: 0478734ff7be75adde8d160e04872664d1c62e5f
  mode: pip-vcs
jestimator:
  url: https://github.com/google-research/jestimator.git
  tracking_ref: main
  latest_verified_commit: 326824a477feef6d92e6f44175000907a72899ca
  mode: pip-vcs
optax:
  url: https://github.com/google-deepmind/optax.git
  tracking_ref: main
  latest_verified_commit: 457018cf47e882688cc3f15ca8e84e1b2ba97220
  mode: pip-vcs
seqio:
  url: https://github.com/google/seqio.git
  tracking_ref: main
  latest_verified_commit: 48180c68c5fc8ddb15bc98467c388a2132e69983
  mode: pip-vcs
maxtext:
  url: https://github.com/google/maxtext.git
  tracking_ref: main
  latest_verified_commit: |-
    b86dfb690629f5f5cda7c39eb397782f2c9a99c6
    1adb45ce021c39103c0266854189f47f79c88386
  mode: git-clone
mlperf-logging:
  url: https://github.com/mlcommons/logging.git
  tracking_ref: master
  latest_verified_commit: a4e663c895ddf57bec931394a1f92e7b1c32fd72
  mode: pip-vcs
equinox:
  url: https://github.com/patrick-kidger/equinox.git
  tracking_ref: main
  latest_verified_commit: 87f4072b5a54c99b30e9a53f8eb97ba3a2e8b46f
  mode: git-clone
orbax-checkpoint:
  url: https://github.com/google/orbax.git
  tracking_ref: main
  latest_verified_commit: 38eed261d60152418b03636c5a34bc6bc0ada291
  mode: pip-vcs
pathwaysutils:
  url: https://github.com/google/pathways-utils.git
  tracking_ref: main
  latest_verified_commit: e04f03d63ce6c6f975a0e347357cff7b7cd08ab1
  mode: pip-vcs
axlearn:
  url: https://github.com/apple/axlearn.git
  mirror_url: https://github.com/nvjax-svc-0/axlearn.git
  tracking_ref: main
  mode: git-clone
  latest_verified_commit: b4797145d672eec5a5dcc52f1dfada46963de509
qwix:
  url: https://github.com/google/qwix.git
  tracking_ref: main
  latest_verified_commit: 44d0f5230cc5e67e36cb3f16e33fcf6d21381e2f
  mode: git-clone
tunix:
  url: https://github.com/google/tunix.git
  tracking_ref: main
  latest_verified_commit: 261535dc1622de98b367af0f177d16dc514d4fab
  mode: git-clone
torchax:
  url: https://github.com/google/torchax.git
  tracking_ref: main
  latest_verified_commit: 9ce5f2d36a7e4220c609e152a98a7cfb6bc68335
  mode: git-clone
