jax:
  url: https://github.com/google/jax.git
  tracking_ref: main
  latest_verified_commit: 757a80d7b35c54f10d15a817f6c129eb5b5d0137
  mode: git-clone
xla:
  url: https://github.com/openxla/xla.git
  tracking_ref: main
  latest_verified_commit: dc97facce8a6458ec4ca6ca8eb763272561827e3
  mode: git-clone
flax:
  url: https://github.com/google/flax.git
  mirror_url: https://github.com/nvjax-svc-0/flax.git
  tracking_ref: main
  mode: git-clone
  patches:
    pull/3340/head: file://patches/flax/PR-3340.patch # Add Sharding Annotations to Flax Modules
  latest_verified_commit: 35d911a265b945b941ce7369e58f5fe3fc8b6214
transformer-engine:
  url: https://github.com/NVIDIA/TransformerEngine.git
  tracking_ref: main
  latest_verified_commit: e879bf87af032cb919f4851b913f3573c730c748
  mode: git-clone
pydantic:
  version: X.Y.Z
  mode: pip-constraint
dllogger:
  url: https://github.com/NVIDIA/dllogger.git
  tracking_ref: master
  latest_verified_commit: 0478734ff7be75adde8d160e04872664d1c62e5f
  mode: pip-vcs
jestimator:
  url: https://github.com/google-research/jestimator.git
  tracking_ref: main
  latest_verified_commit: 326824a477feef6d92e6f44175000907a72899ca
  mode: pip-vcs
optax:
  url: https://github.com/google-deepmind/optax.git
  tracking_ref: main
  latest_verified_commit: 36d72acf40c5cb5ba06cdafa9c19c94074c98110
  mode: pip-vcs
seqio:
  url: https://github.com/google/seqio.git
  tracking_ref: main
  latest_verified_commit: db78942f10f9937ed42d42adf94c7f669b36fc84
  mode: pip-vcs
maxtext:
  url: https://github.com/google/maxtext.git
  tracking_ref: main
  latest_verified_commit: de510213afe8e76acd3a9c6a8634285c9077d60a
  mode: git-clone
mlperf-logging:
  url: https://github.com/mlcommons/logging.git
  tracking_ref: master
  latest_verified_commit: 34903058ee63d3a7c3bcc1a6ca04e2aa5ed6af9c
  mode: pip-vcs
equinox:
  url: https://github.com/patrick-kidger/equinox.git
  tracking_ref: main
  latest_verified_commit: d79fd7523c99a1e92412e0c78af665e913555e1b
  mode: git-clone
orbax-checkpoint:
  url: https://github.com/google/orbax.git
  tracking_ref: main
  latest_verified_commit: c7bb957387d2b154d571035faae42f7f6b92c612
  mode: pip-vcs
pathwaysutils:
  url: https://github.com/google/pathways-utils.git
  tracking_ref: main
  latest_verified_commit: 44d0853a9d29f05f2d1a1800b8416178cc7c853d
  mode: pip-vcs
axlearn:
  url: https://github.com/apple/axlearn.git
  mirror_url: https://github.com/nvjax-svc-0/axlearn.git
  tracking_ref: main
  mode: git-clone
  latest_verified_commit: 5602a78f9ccd2e13da6b9a2c751d916c73e62a92
qwix:
  url: https://github.com/google/qwix.git
  tracking_ref: main
  latest_verified_commit: 3928dfd488a3ca3db58610d030f4c110c745efbd
  mode: git-clone
tunix:
  url: https://github.com/google/tunix.git
  tracking_ref: main
  latest_verified_commit: a52883ea40d32f0d3ac8eb16e13a6c9fed2f0174
  mode: git-clone
torchax:
  url: https://github.com/google/torchax.git
  tracking_ref: main
  latest_verified_commit: 060df56a6c9996fdd99cf915efca3fbb422359cf
  mode: git-clone
