jax:
  url: https://github.com/google/jax.git
  tracking_ref: main
  latest_verified_commit: 4f22f9d2fd90f21f350a8d9ab1a21421502024ca
  mode: git-clone
xla:
  url: https://github.com/openxla/xla.git
  tracking_ref: main
  latest_verified_commit: 964a0a45a0c3090cd484a3c51e8f9d05ed10b968
  mode: git-clone
flax:
  url: https://github.com/google/flax.git
  mirror_url: https://github.com/nvjax-svc-0/flax.git
  tracking_ref: main
  mode: git-clone
  patches:
    pull/3340/head: file://patches/flax/PR-3340.patch # Add Sharding Annotations to Flax Modules
  latest_verified_commit: 3ae65afec3585688e28ca7d14d9ab95007294f9f
transformer-engine:
  url: https://github.com/NVIDIA/TransformerEngine.git
  tracking_ref: main
  latest_verified_commit: 57b5b6076d568a7a189a40e592ceea40cdf34cec
  mode: git-clone
pydantic:
  version: X.Y.Z
  mode: pip-constraint
dllogger:
  url: https://github.com/NVIDIA/dllogger.git
  tracking_ref: master
  latest_verified_commit: 0478734ff7be75adde8d160e04872664d1c62e5f
  mode: pip-vcs
jestimator:
  url: https://github.com/google-research/jestimator.git
  tracking_ref: main
  latest_verified_commit: 326824a477feef6d92e6f44175000907a72899ca
  mode: pip-vcs
optax:
  url: https://github.com/google-deepmind/optax.git
  tracking_ref: main
  latest_verified_commit: 7a58a58f9e061be8d0fe7439431942f8bc9a7f8d
  mode: pip-vcs
seqio:
  url: https://github.com/google/seqio.git
  tracking_ref: main
  latest_verified_commit: db78942f10f9937ed42d42adf94c7f669b36fc84
  mode: pip-vcs
maxtext:
  url: https://github.com/google/maxtext.git
  tracking_ref: main
  latest_verified_commit: 3737eb35266833cbfffd96a143f126c0c41a6baa
  mode: git-clone
mlperf-logging:
  url: https://github.com/mlcommons/logging.git
  tracking_ref: master
  latest_verified_commit: 346e6046e16148ed095ffce5d9650f20e83b6858
  mode: pip-vcs
equinox:
  url: https://github.com/patrick-kidger/equinox.git
  tracking_ref: main
  latest_verified_commit: b0556e1dfc27f7a63041babe2722396d6d1c56aa
  mode: git-clone
orbax-checkpoint:
  url: https://github.com/google/orbax.git
  tracking_ref: main
  latest_verified_commit: daca63519b7e637f4dc679058ba143676bc85110
  mode: pip-vcs
pathwaysutils:
  url: https://github.com/google/pathways-utils.git
  tracking_ref: main
  latest_verified_commit: b752db70e54697807768a7af7ab6931d054e4f29
  mode: pip-vcs
axlearn:
  url: https://github.com/apple/axlearn.git
  mirror_url: https://github.com/nvjax-svc-0/axlearn.git
  tracking_ref: main
  mode: git-clone
  latest_verified_commit: 5602a78f9ccd2e13da6b9a2c751d916c73e62a92
qwix:
  url: https://github.com/google/qwix.git
  tracking_ref: main
  latest_verified_commit: 6b0fa93425c7597b4875ff175889addb7b6787b5
  mode: git-clone
tunix:
  url: https://github.com/google/tunix.git
  tracking_ref: main
  latest_verified_commit: ac0f4c4acde63a93c5e0973af922f84db5dab5ba
  mode: git-clone
torchax:
  url: https://github.com/google/torchax.git
  tracking_ref: main
  latest_verified_commit: 6a4024f659e97e7e32e0f7b9b73c27355f41e483
  mode: git-clone
